### ISSUE TITLE
replacement could be empty string

### ISSUE THREAD

**Issue by sun51586** [DevNambi/sql-server-regex#1]
Good Job!
1,Usually Replace function need replace something to empty,please fix .
2,download for 2008 ,2005 dll cannot execute 1load-assembly.sql,because the sqlserver didn't support .net 4.0.
TKS.

**Comment by DevNambi** [comment]
Can you give an example (screenshot or code) of what you mean for #1?

**Comment by DevNambi** [comment]
I've updated the SQL 2005 and 2008 DLLs after they were compiled using .NET 2.0. They should work now. I haven't been able to test them since I don't have SQL installs that old.

**Comment by sun51586** [comment]
Sorry for late reply，code is below ,test please：
public static SqlString Replace(String input, String pattern, String replacement)
{
    if (String.IsNullOrEmpty(input) || String.IsNullOrEmpty(pattern) || String.IsNullOrEmpty(replacement))
    {
        return new SqlString(null);
    }
    else
    {
        return new SqlString(Regex.Replace(input, pattern, replacement));
    }
}
****replace with:
//usually replacement parameter is empty string(ex:"")
public static SqlString Replace(String input, String pattern, String replacement)
{
    if (String.IsNullOrEmpty(input) || String.IsNullOrEmpty(pattern))
    {
        return new SqlString(null);
    }
    else
    {
        var rep1 = replacement ?? "";
        return new SqlString(Regex.Replace(input, pattern, rep1));
    }
}

**Comment by DevNambi** [comment]
Oh, I see. Thanks for the code snippet. I'll get it built into the codebase soon, likely sometime this week.

**Comment by DevNambi** [comment]
Fix build, tested, and checked in. DLLs updated.
